const http2 = require('http2');

const {
  HTTP_STATUS_CREATED: SUCCESS_CREATED,
  HTTP_STATUS_BAD_REQUEST: ERROR_BAD_REQUEST,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: ERROR_SERVER,
  HTTP_STATUS_NOT_FOUND: ERROR_NOT_FOUND,
} = http2.constants;

module.exports = {
  SUCCESS_CREATED,
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_SERVER
};


// const ERROR_BAD_REQUEST = 400;
// const ERROR_NOT_FOUND = 404;
// const ERROR_SERVER = 500;

// const SUCCESS_CREATED = 201;

// module.exports = {
//   ERROR_BAD_REQUEST, ERROR_NOT_FOUND, ERROR_SERVER, SUCCESS_CREATED,
// };
